#!/system/bin/sh

# Frandom
rm -f /dev/urandom
ln -s /dev/erandom /dev/urandom
rm -f /dev/random
ln -s /dev/erandom /dev/random

# Seeder
mount -o remount,rw -t auto /data
/starkissed/rngd
sleep 2
echo -8 > /proc/$(pgrep /sbin/sku/rngd)/oom_adj
renice +8 /sbin/sku/rngd