#!/system/bin/sh

# custom carrier configuration
export carrier=`getprop ro.product.device`
if [ "$carrier" == "trlteatt" ]; then

elif [ "$carrier" == "trltecan" ]; then

elif [ "$carrier" == "trltespr" ]; then

elif [ "$carrier" == "trltetmo" ]; then

elif [ "$carrier" == "trlteusc" ]; then

elif [ "$carrier" == "trltevzw" ]; then

fi